name: Scrape Sector & Stock

on:
  schedule:
    - cron: "*/10 5-9 * * 0-4"
  workflow_dispatch:

jobs:
  sector:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      CENTRAL_REPO_OWNER: <YOUR-USERNAME>
      CENTRAL_REPO_NAME: nepse-central
      CENTRAL_REPO_TOKEN: ${{ secrets.CENTRAL_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run sector scraper
        env:
          FORCE_RUN: "true"
        run: node sector.js

  stock:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      CENTRAL_REPO_OWNER: <YOUR-USERNAME>
      CENTRAL_REPO_NAME: nepse-central
      CENTRAL_REPO_TOKEN: ${{ secrets.CENTRAL_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run stock scraper
        env:
          FORCE_RUN: "true"
        run: node stock.js
